export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const FECTH_MESSSAGE_SUCCESS = 'FECTH_MESSSAGE_SUCCESS';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';

